name: ci

on: [ push, pull_request ]

jobs:
  inspection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: pip install flake8
      - run: pip install mypy
      - run: flake8 sin.py sinner
      - run: mypy --config-file mypy.ini sin.py sinner
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: |
          pip install numpy>=1.24.3 --verbose
          pip install opencv-python>=4.8.0.74 --verbose
          pip install onnx==1.14.0 --verbose
          pip install insightface==0.7.3 --verbose
          pip install psutil==5.9.5 --verbose
          pip install tk==0.1.0 --verbose
          pip install customtkinter==5.2.0 --verbose
          pip install torch==2.0.1 --verbose
          pip install torchvision==0.15.2 --verbose
          pip install onnxruntime==1.15.1 --verbose
          pip install tensorflow~=2.13.0rc1 --verbose
          pip install protobuf>=4.24.1 --verbose
          pip install tqdm>=4.65.0 --verbose
          pip install pytest==7.4.0 --verbose
          pip install gfpgan==1.3.8 --verbose
          pip install colorama~=0.4.6 --verbose
      - run: |
          export DISPLAY=:1:0
          Xvfb :1 -screen 0 1600x1200x16 &
      - run: pytest -m "not skip"

