name: ci

on: [ push ]

jobs:
  not_supported_warn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: |
          output=$(python sin.py)
          if [[ $output == *"Python version is not supported"* ]]; then
            echo "Warn is here!"
            exit 0  # Success status code
          else
            echo "No warn found"
            exit 1  # Failure status code
          fi
  inspection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: pip install flake8
      - run: pip install mypy
      - run: flake8 sin.py sinner
      - run: mypy --config-file mypy.ini sin.py sinner
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: df -h
      - run: python -m site --user-site
      - run: |
          pip install numpy>=1.24.3
          pip install opencv-python>=4.8.0.74
          pip install onnx==1.14.0
          pip install insightface==0.7.3
          pip install psutil==5.9.5
          pip install tk==0.1.0
          pip install customtkinter==5.2.0
          pip install torch==2.0.1
          pip install torchvision==0.15.2
          pip install onnxruntime==1.15.1
          pip install tensorflow==2.17.0
          pip install protobuf>=4.24.1
          pip install tqdm>=4.65.0
          pip install pytest==7.4.0
          pip install gfpgan==1.3.8
          pip install colorama~=0.4.6
          pip install pyvirtualcam
          pip install pathvalidate
          pip install pygame
          pip install moviepy>=1.0.4
          pip install python-vlc
          pip install zmq
      - run: |
          export DISPLAY=:1:0
          Xvfb :1 -screen 0 1600x1200x16 &
      - run: pytest -m "not skip" -vv --tb=long

